namespace LanguagesEnum
{
    public class LanguagesEnumClass
    {
        public const string
            Turkish = "tr",
            English = "en",
            Amharic = "am",
            Arabic = "ar",
            Basque = "eu",
            Bengali = "bn",
            EnglishUK = "en-GB",
            PortugueseBrazil = "pt-BR",
            Bulgarian = "bg",
            Catalan = "ca",
            Cherokee = "chr",
            Croatian = "hr",
            Czech = "cs",
            Danish = "da",
            Dutch = "nl",
            Estonian = "et",
            Filipino = "fil",
            Finnish = "fi",
            French = "fr",
            German = "de",
            Greek = "el",
            Gujarati = "gu",
            Hebrew = "iw",
            Hindi = "hi",
            Hungarian = "hu",
            Icelandic = "is",
            Indonesian = "id",
            Italian = "it",
            Japanese = "ja",
            Kannada = "kn",
            Korean = "ko",
            Latvian = "lv",
            Lithuanian = "lt",
            Malay = "ms",
            Malayalam = "ml",
            Marathi = "mr",
            Norwegian = "no",
            Polish = "pl",
            Portuguese = "pt-PT",
            Romanian = "ro",
            Russian = "ru",
            Serbian = "sr",
            Chinese = "zh-CN",
            Slovak = "sk",
            Slovenian = "sl",
            Spanish = "es",
            Swahili = "sw",
            Swedish = "sv",
            Tamil = "ta",
            Telugu = "te",
            Thai = "th",
            ChineseTaiwan = "zh-TW",
            Urdu = "ur",
            Ukrainian = "uk",
            Vietnamese = "vi",
            Welsh = "cy";
    }

}